"""Protocol definitions for liquidations feed components."""

from collections.abc import AsyncGenerator
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class NetworkClientProtocol(Protocol):
    async def ws_connect(self, url: str) -> "WSAssistantProtocol": ...
    async def rest_get(self, url: str, params: dict | None = None) -> Any: ...
    async def close(self) -> None: ...


@runtime_checkable
class WSAssistantProtocol(Protocol):
    async def send(self, payload: Any) -> None: ...
    async def disconnect(self) -> None: ...
    def iter_messages(self) -> AsyncGenerator[Any, None]: ...
